version: "3.9"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home_chore_bot
    environment:
      - TELEGRAM_BOT_TOKEN
      - DB_URL
    restart: unless-stopped
